"""Add tenand table and tenand id column in jobs

Revision ID: f7c86b0e1f7c
Revises: 14c63a5b720b
Create Date: 2026-05-07 11:23:36.674737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7c86b0e1f7c'
down_revision: Union[str, Sequence[str], None] = '14c63a5b720b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_api_key'), 'tenants', ['api_key'], unique=False)
    op.add_column('jobs', sa.Column('tenant_id', sa.String(), nullable=True))

    # Setting the existing jobs to default tenant
    op.execute("INSERT INTO tenants(id, name, api_key) VALUES('default-uuid', 'Legacy Tenant', 'init-key-hash')")
    op.execute("UPDATE jobs SET tenant_id = 'default-uuid' WHERE tenant_id IS NULL")

    op.create_index(op.f('ix_jobs_tenant_id'), 'jobs', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'jobs', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_index(op.f('ix_jobs_tenant_id'), table_name='jobs')
    op.drop_column('jobs', 'tenant_id')
    op.drop_index(op.f('ix_tenants_api_key'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
